#pragma config(Sensor, dgtl11, Solenoid,       sensorDigitalOut)
#pragma config(Sensor, dgtl12, Solenoid,       sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*SensorValue[dgtl11]=0;
	SensorValue[dgtl12]=1;
	wait1Msec(100);
	SensorValue[dgtl11]=1;
	SensorValue[dgtl12]=0;
	wait1Msec(100);
	SensorValue[dgtl11]=0;
	SensorValue[dgtl12]=0;
	wait1Msec(100);*/
wait1Msec(5000);
if(Btn8U){//if up on channel 8, set relay to forward
	SensorValue[dgtl11]=0;
	SensorValue[dgtl12]=1;
	wait1Msec(100);
} else if(Btn8D){
	SensorValue[dgtl11]=1;
	SensorValue[dgtl12]=0;
	wait1Msec(100);//if down on channel 8, set relay to reverse
} else if(Btn8L){
	SensorValue[dgtl11]=0;
	SensorValue[dgtl12]=0;
	wait1Msec(100);//if left on channel 8. set relay to off
}
}
/*
//ALL OF THIS(below) IS COPIED AND PASTED FROM CHIEF DELPHI AND HAS ERRORS//

while(frcOIJoystickButtons[oiButtonPort3Button3] == 1) //
{
frcRelay[relay1] = relayFwd; // turn on compressor
//frcRelay[relay1] = relayOff; turn off
}
while(frcOIJoystickButtons[oiButtonPort3Button4] == 1) //
{
frcRelay[relay1] = relayOff; // turn on compressor
//frcRelay[relay1] = relayOff; turn off
}
while(frcOIJoystickButtons[oiButtonPort3Button1] == 1) // piston
{
frcRelay[relay2Fwd] = true;//
frcRelay[relay2Rvs] = false;
}
while(frcOIJoystickButtons[oiButtonPort3Button2] == 1) //piston
{
frcRelay[relay2]=relayRvs;
//
//frcRelay[relay1] = relayOff; turn off
}
*/
/* while(frcOIJoystickButtons[oiButtonPort3Button1] == 1) //bottom left button
{
frcDigitalIOValue[pio1] = true; //to turn the output on (activate the solenoid)
//frcDigitalIOValue[pio3] = 0; turn off
}
while(frcOIJoystickButtons[oiButtonPort3Button2] == 1) //bottom left button
{
frcDigitalIOValue[pio1] = false;
}
*/
/*
while(frcOIJoystickButtons[oiButtonPort1Button3] == 1) //top left button
{
// motor[port1] = -25;
// motor[port2] = -25;
//wait1Msec(10);
}
while(frcOIJoystickButtons[oiButtonPort1Button4] == 1) //top right button
{
// motor[port1] = -50;
//motor[port2] = -50;
//wait1Msec(10);
}
*/
